ip: 192.168.0.104
server:
  port: 8781
  address: ${ip}
eureka:
  instance:
    hostname: ${ip}
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
spring:
  application:
    name: order-server
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      shutdown-timeout: 1000
  zipkin:
    base-url: http://${ip}:9411
  sleuth:
    sampler:
      probability: 1
PRODUCT-SERVER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    ReadTimeout: 4000
#设置feign的响应时间
feign:
  client:
    config:
      default:
        connectTimeout: 4000
        readTimeout: 4000
  hystrix:
    enabled: true

#设置hystrix超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
#配置hystrix页面
management:
  endpoints:
    web:
      exposure:
        include: "*"